### ISSUE TITLE
caught Error: env variable 0x5FbDB2315678afecb367f032d93F642f64180aa3 not defined  

### ISSUE THREAD

**Issue by levi-1010-byte** [DevelopersLeague/EtherDocs#2]
![image](https://user-images.githubusercontent.com/80025240/235660143-52cbe62e-7220-48f4-bd83-51c572e5dc99.png)
my server is properly working but i am getting this error in console after already making file of .env.local

**Comment by ShyrenMore** [comment]
You probably have written the address directly, it's suppose to be `REACT_APP_CONTRACT_ADDRESS=your_address`

**Comment by ShyrenMore** [comment]
Hey @levi-1010-byte (Harshit) due to no reply, I am assuming the error was resolved hence closing this issue
